export const USER_INTERFACE_ID = 'user-interface';
export const INFO_WINDOW_ID = 'info-window';
export const CONTINUE_BUTTON_ID = 'continue-button';
export const SEARCH_BUTTON_ID = 'search-button';
export const OPEN_INFO_BUTTON_ID = 'open-info-button';
export const CLOSE_INFO_BUTTON_ID = 'close-info-button';
export const MAP_DIV_ID = 'map';
export const GBIF_OCCURRENCE_URL =
  'https://api.gbif.org/v1/occurrence/search?year=2000,2023';
